title: FFMPEG_HDF5_FILTER
description: An HDF5 Plugin Utilizing Advanced Video Codecs for Biomedical Image Compression.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: https://www.cai-lab.org/
repo_url: "https://github.com/Cai-Lab-at-University-of-Michigan/ffmpeg_HDF5_filter"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
plugins:
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock