name: Build and Publish Wheels

permissions:
  contents: write

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        # ubuntu-latest is x86_64, macos-latest is apple silicon
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (Linux only)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Debug Environment
        shell: bash
        run: |
          echo "=== System Information ==="
          echo "OS: ${{ matrix.os }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Architecture: $(uname -m)"
          echo "Python version: ${{ env.PYTHON_VERSION }}"
          echo "=== Available disk space ==="
          df -h
          echo "=== Current directory ==="
          pwd
          ls -la

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3

      - name: Debug Build Results
        shell: bash
        run: |
          echo "=== Build Results ==="
          ls -la ./wheelhouse/ || echo "No wheelhouse directory"
          echo "=== FFmpeg Installation Check ==="
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ls -la D:/a/ffmpeg_build/ || echo "No Windows FFmpeg build"
            if [[ -f "D:/a/ffmpeg_build/bin/ffmpeg.exe" ]]; then
              echo "FFmpeg found on Windows"
            else
              echo "FFmpeg NOT found on Windows"
            fi
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            ls -la ~/ffmpeg/ || echo "No macOS FFmpeg build"
            if [[ -f "$HOME/ffmpeg/bin/ffmpeg" ]]; then
              echo "FFmpeg found on macOS"
            else
              echo "FFmpeg NOT found on macOS"
            fi
          else
            ls -la /opt/ffmpeg/ || echo "No Linux FFmpeg build"
            if [[ -f "/opt/ffmpeg/bin/ffmpeg" ]]; then
              echo "FFmpeg found on Linux"
            else
              echo "FFmpeg NOT found on Linux"
            fi
          fi

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          retention-days: 7

  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
      
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz
          retention-days: 7

  assemble_java:
    name: Assemble Java JAR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check if Java project exists
        run: |
          if [[ ! -d "imagej-hdf5-wrapper" ]]; then
            echo "ERROR: imagej-hdf5-wrapper directory not found"
            echo "Available directories:"
            ls -la
            exit 1
          fi

      - name: Build JAR with Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle build
        working-directory: imagej-hdf5-wrapper
        run: ./gradlew packJar --no-daemon

      - name: Verify JAR contents
        run: |
          echo "=== Verifying JAR contents ==="
          JAR_FILE=$(find imagej-hdf5-wrapper/build/libs -name "HDF5-ffmpeg-*.jar" | head -1)
          
          if [[ -f "$JAR_FILE" ]]; then
            echo "JAR file: $JAR_FILE"
            echo "JAR size: $(du -h "$JAR_FILE" | cut -f1)"
            echo "=== JAR structure ==="
            unzip -l "$JAR_FILE" | head -20
          else
            echo "ERROR: JAR file not found"
            find imagej-hdf5-wrapper/build -name "*.jar" || echo "No JAR files found"
            exit 1
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: hdf5-ffmpeg-jar
          path: imagej-hdf5-wrapper/build/libs/HDF5-ffmpeg-*.jar

  publish:
    name: Publish to PyPI and GitHub Releases
    needs: [build_wheels, build_sdist, assemble_java]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)) || github.event_name == 'workflow_dispatch'
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install publishing tools
        run: |
          python -m pip install --upgrade pip twine
          mkdir -p dist java-dist

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Collect wheels and sdist
        run: |
          # Move all wheels to dist/
          find artifacts/ -name "*.whl" -exec cp {} dist/ \;
          
          # Move sdist to dist/
          find artifacts/sdist/ -name "*.tar.gz" -exec cp {} dist/ \; 2>/dev/null || true
          
          # Move JAR to java-dist/
          find artifacts/hdf5-ffmpeg-jar/ -name "*.jar" -exec cp {} java-dist/ \; 2>/dev/null || true
          
          echo "=== Distribution files ==="
          ls -la dist/
          echo "=== Java files ==="
          ls -la java-dist/

      - name: Verify distribution files
        run: |
          echo "=== Checking wheel and sdist integrity ==="
          python -m twine check dist/*.whl dist/*.tar.gz

      - name: Publish to TestPyPI
        if: (github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)) || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          echo "Publishing to TestPyPI..."
          python -m twine upload --repository testpypi dist/*.whl dist/*.tar.gz --verbose

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Publishing to PyPI..."
          python -m twine upload dist/*.whl dist/*.tar.gz --verbose

      - name: Delete previous snapshot release
        if: github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: snapshot-${{ github.ref_name }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Get timestamp for snapshot
        id: timestamp
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref))
        uses: softprops/action-gh-release@v2
        with:
          files: |
            java-dist/*.jar
            dist/*.whl
            dist/*.tar.gz
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('snapshot-{0}', github.ref_name) }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('Snapshot {0} ({1})', github.ref_name, steps.timestamp.outputs.timestamp) }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          draft: false
          body: |
            ${{ !startsWith(github.ref, 'refs/tags/') && format('Development build from {0} branch
            
            **Commit:** {1}
            **Created:** {2}
            
            This is an automated snapshot build. Use at your own risk.', github.ref_name, github.sha, steps.timestamp.outputs.timestamp) || 'Release build' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}