name: Build and Publish Wheels

permissions:
  contents: write

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (Linux only)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Debug Environment
        shell: bash
        run: |
          echo "=== System Information ==="
          echo "OS: ${{ matrix.os }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Architecture: $(uname -m)"
          echo "Python version: ${{ env.PYTHON_VERSION }}"
          echo "=== Available disk space ==="
          df -h
          echo "=== Current directory ==="
          pwd
          ls -la

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3

      - name: Package libraries for shared lib build
        shell: bash
        run: |
          echo "=== Packaging complete build environment for shared library build ==="
          mkdir -p shared_lib_package
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "Packaging Windows complete build environment..."
            if [[ -d "D:/a/ffmpeg_build" ]]; then
              cp -r D:/a/ffmpeg_build/* shared_lib_package/ 2>/dev/null || echo "Error copying Windows build"
            else
              echo "WARNING: D:/a/ffmpeg_build not found"
            fi
            
            echo "Windows package structure:"
            find shared_lib_package/ -type d | head -10 || echo "Error listing directories" 
            echo "Key files:"
            find shared_lib_package/ -name "*.pc" -o -name "*.cmake" -o -name "*.dll" -o -name "*.lib" 2>/dev/null | head -20 || echo "No key files found"
            
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "Packaging macOS complete build environment..."
            
            echo "=== Checking macOS directories ==="
            ls -la ~/ | grep -E "(ffmpeg|miniconda)" || echo "No ffmpeg/miniconda dirs in home"
            ls -la ~/ffmpeg/ || echo "~/ffmpeg not found"
            ls -la ~/miniconda/ || echo "~/miniconda not found"
            
            if [[ -d "$HOME/ffmpeg" ]]; then
              mkdir -p shared_lib_package/ffmpeg
              cp -r ~/ffmpeg/* shared_lib_package/ffmpeg/ 2>/dev/null || echo "Error copying FFmpeg"
              echo "Copied FFmpeg from ~/ffmpeg"
            else
              echo "WARNING: ~/ffmpeg not found"
            fi
            
            if [[ -d "$HOME/miniconda" ]]; then
              mkdir -p shared_lib_package/miniconda
              cp -r ~/miniconda/lib shared_lib_package/miniconda/ 2>/dev/null || echo "Error copying conda lib"
              cp -r ~/miniconda/include shared_lib_package/miniconda/ 2>/dev/null || echo "Error copying conda include"
              cp -r ~/miniconda/share shared_lib_package/miniconda/ 2>/dev/null || echo "Error copying conda share"
              cp -r ~/miniconda/bin shared_lib_package/miniconda/ 2>/dev/null || echo "Error copying conda bin"
              echo "Copied conda from ~/miniconda"
            else
              echo "WARNING: ~/miniconda not found"
            fi
            
            echo "macOS package structure:"
            find shared_lib_package/ -type d 2>/dev/null | head -10 || echo "Error listing directories"
            echo "Key files:"
            find shared_lib_package/ -name "*.pc" -o -name "*.cmake" -o -name "*.dylib" 2>/dev/null | head -20 || echo "No key files found"
            
          else
            echo "Packaging Linux libraries from copied build archive..."
            
            if [[ -f "./build_deps.tar.gz" ]]; then
              echo "Found build archive, extracting..."
              tar -xzf ./build_deps.tar.gz
              
              if [[ -d "./ffmpeg" ]]; then
                mkdir -p shared_lib_package/ffmpeg
                cp -r ./ffmpeg/* shared_lib_package/ffmpeg/ 2>/dev/null || echo "Error copying FFmpeg"
                echo "Copied FFmpeg from archive"
              fi
              
              if [[ -d "./miniconda" ]]; then
                mkdir -p shared_lib_package/miniconda
                cp -r ./miniconda/* shared_lib_package/miniconda/ 2>/dev/null || echo "Error copying conda"
                echo "Copied conda from archive"
              fi
              
            else
              echo "No build archive found, extracting from wheel as fallback..."
              wheel_file=$(find ./wheelhouse/ -name "*.whl" | head -1)
              if [[ -n "$wheel_file" ]]; then
                echo "Extracting from wheel: $wheel_file"
                mkdir -p wheel_extracted
                python -m zipfile -e "$wheel_file" wheel_extracted/
                cp -r wheel_extracted/* shared_lib_package/ 2>/dev/null || echo "Error copying wheel contents"
                echo "Copied entire wheel structure"
              else
                echo "ERROR: No wheel file found for extraction"
              fi
            fi
            
            echo "Linux package structure:"
            find shared_lib_package/ -type d | head -10 || echo "Error listing directories"
            echo "Key files:"
            find shared_lib_package/ -name "*.pc" -o -name "*.so*" 2>/dev/null | head -20 || echo "No key files found"
          fi
          
          tar -czf shared_lib_deps_${{ matrix.os }}.tar.gz -C shared_lib_package .
          
          echo "=== Package created ==="
          ls -la shared_lib_deps_${{ matrix.os }}.tar.gz

      - name: Debug Build Results
        shell: bash
        run: |
          echo "=== Build Results ==="
          ls -la ./wheelhouse/ || echo "No wheelhouse directory"
          echo "=== FFmpeg Installation Check ==="
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ls -la D:/a/ffmpeg_build/ || echo "No Windows FFmpeg build"
            if [[ -f "D:/a/ffmpeg_build/bin/ffmpeg.exe" ]]; then
              echo "FFmpeg found on Windows"
            else
              echo "FFmpeg NOT found on Windows"
            fi
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            ls -la ~/ffmpeg/ || echo "No macOS FFmpeg build"
            if [[ -f "$HOME/ffmpeg/bin/ffmpeg" ]]; then
              echo "FFmpeg found on macOS"
            else
              echo "FFmpeg NOT found on macOS"
            fi
          else
            ls -la /opt/ffmpeg/ || echo "No Linux FFmpeg build"
            if [[ -f "/opt/ffmpeg/bin/ffmpeg" ]]; then
              echo "FFmpeg found on Linux"
            else
              echo "FFmpeg NOT found on Linux"
            fi
          fi

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          retention-days: 7

      - name: Upload shared lib dependencies
        uses: actions/upload-artifact@v4
        with:
          name: shared-lib-deps-${{ matrix.os }}-${{ strategy.job-index }}
          path: shared_lib_deps_${{ matrix.os }}.tar.gz
          retention-days: 7

  build_shared_libs:
    name: Build shared libraries on ${{ matrix.os }}
    needs: [build_wheels]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y cmake build-essential patchelf
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cmake
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          fi

      - name: Download shared lib dependencies
        uses: actions/download-artifact@v4
        with:
          name: shared-lib-deps-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./deps_archive/

      - name: Extract dependencies
        shell: bash
        run: |
          echo "=== Extracting dependencies ==="
          mkdir -p deps
          cd deps_archive
          tar -xzf shared_lib_deps_${{ matrix.os }}.tar.gz -C ../deps/
          
          echo "=== Available libraries ==="
          find ../deps/ -name "*.so*" -o -name "*.dylib" -o -name "*.dll" -o -name "*.lib" | head -20
          
          echo "=== Available headers ==="
          find ../deps/ -name "*.h" | head -10

      - name: Build shared library
        shell: bash
        run: |
          echo "=== Building shared library ==="
          mkdir build
          cd build
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cmake .. -G "Visual Studio 17 2022" -A x64
            cmake --build . --config Release
            cmake --install . --prefix ../install --config Release
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build . --target bundle_all
            cmake --install . --prefix ../install
          fi
          
          echo "=== Build completed ==="
          find ../install/ -type f | head -20

      - name: Package shared library bundle
        shell: bash
        run: |
          echo "=== Creating final package ==="
          cd install
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a -tzip "../h5ffmpeg_shared_bundle_Windows.zip" .
          else
            tar -czf "../h5ffmpeg_shared_bundle_${{ runner.os }}.tar.gz" .
          fi
          
          cd ..
          echo "=== Package created ==="
          ls -la h5ffmpeg_shared_bundle_*

      - name: Upload shared library bundle
        uses: actions/upload-artifact@v4
        with:
          name: shared-lib-bundle-${{ matrix.os }}
          path: |
            h5ffmpeg_shared_bundle_*.zip
            h5ffmpeg_shared_bundle_*.tar.gz
          retention-days: 7

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
      
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz
          retention-days: 7

  assemble_java:
    name: Assemble Java JAR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check if Java project exists
        run: |
          if [[ ! -d "imagej-hdf5-wrapper" ]]; then
            echo "ERROR: imagej-hdf5-wrapper directory not found"
            echo "Available directories:"
            ls -la
            exit 1
          fi

      - name: Build JAR with Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle build
        working-directory: imagej-hdf5-wrapper
        run: ./gradlew packJar --no-daemon

      - name: Verify JAR contents
        run: |
          echo "=== Verifying JAR contents ==="
          JAR_FILE=$(find imagej-hdf5-wrapper/build/libs -name "HDF5-ffmpeg-*.jar" | head -1)
          
          if [[ -f "$JAR_FILE" ]]; then
            echo "JAR file: $JAR_FILE"
            echo "JAR size: $(du -h "$JAR_FILE" | cut -f1)"
            echo "=== JAR structure ==="
            unzip -l "$JAR_FILE" | head -20
          else
            echo "ERROR: JAR file not found"
            find imagej-hdf5-wrapper/build -name "*.jar" || echo "No JAR files found"
            exit 1
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: hdf5-ffmpeg-jar
          path: imagej-hdf5-wrapper/build/libs/HDF5-ffmpeg-*.jar

  publish:
    name: Publish to PyPI and GitHub Releases
    needs: [build_wheels, build_sdist, assemble_java, build_shared_libs]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)) || github.event_name == 'workflow_dispatch'
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install publishing tools
        run: |
          python -m pip install --upgrade pip twine
          mkdir -p dist java-dist shared-libs-dist

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Collect wheels and sdist
        run: |
          find artifacts/ -name "*.whl" -exec cp {} dist/ \;
          find artifacts/sdist/ -name "*.tar.gz" -exec cp {} dist/ \; 2>/dev/null || true
          find artifacts/hdf5-ffmpeg-jar/ -name "*.jar" -exec cp {} java-dist/ \; 2>/dev/null || true
          find artifacts/shared-lib-bundle-*/ -name "h5ffmpeg_shared_bundle_*" -exec cp {} shared-libs-dist/ \; 2>/dev/null || true
          
          echo "=== Distribution files ==="
          ls -la dist/
          echo "=== Java files ==="
          ls -la java-dist/
          echo "=== Shared library bundles ==="
          ls -la shared-libs-dist/

      - name: Verify distribution files
        run: |
          echo "=== Checking wheel and sdist integrity ==="
          python -m twine check dist/*.whl dist/*.tar.gz

      - name: Publish to TestPyPI
        if: (github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)) || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          echo "Publishing to TestPyPI..."
          python -m twine upload --repository testpypi dist/*.whl dist/*.tar.gz --verbose

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Publishing to PyPI..."
          python -m twine upload dist/*.whl dist/*.tar.gz --verbose

      - name: Delete previous snapshot release
        if: github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: snapshot-${{ github.ref_name }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Get timestamp for snapshot
        id: timestamp
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref))
        uses: softprops/action-gh-release@v2
        with:
          files: |
            java-dist/*.jar
            dist/*.whl
            dist/*.tar.gz
            shared-libs-dist/*
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('snapshot-{0}', github.ref_name) }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('Snapshot {0} ({1})', github.ref_name, steps.timestamp.outputs.timestamp) }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          draft: false
          body: |
            ${{ !startsWith(github.ref, 'refs/tags/') && format('Development build from {0} branch
            
            **Commit:** {1}
            **Created:** {2}
            
            This is an automated snapshot build. Use at your own risk.', github.ref_name, github.sha, steps.timestamp.outputs.timestamp) || 'Release build' }}
            
            ## Available Downloads:
            - **Python Wheels** (.whl) - Install with pip
            - **Source Distribution** (.tar.gz) - Build from source
            - **Java JAR** - ImageJ/Fiji plugin
            - **Shared Library Bundles** - Self-contained C libraries:
              - `h5ffmpeg_shared_bundle_windows.zip` - Windows bundle
              - `h5ffmpeg_shared_bundle_macOS.tar.gz` - macOS bundle  
              - `h5ffmpeg_shared_bundle_Linux.tar.gz` - Linux bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}